version: '3.6'

networks:
  basyx:
    internal: false

volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local
  elasticsearch-data:
    driver: local
  aas-config:
services:  
  portainer:
    image: portainer/portainer:latest
    container_name: basyx-portainer
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - basyx
      
  zookeeper:
    image: zookeeper:3.6
    container_name: basyx-zookeeper
    restart: always
    ports:
      - "2181:2181"  
    volumes:
      #- ./data/zookeeper/conf/zoo.cfg:/conf/zoo.cfg:Z  
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log   
    networks:
      - basyx
      
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: basyx-kafka
    volumes:
      - kafka-data:/var/lib/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # use one protocol in the docker network 
      # and one (PLAINTEXT_HOST) from outside docker, used for testing
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper
    restart: always
    networks:
      - basyx
      
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data     
    environment:
      - discovery.type=single-node  
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - basyx
  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
   # restart: always
    networks:
      - basyx      
               
  aas-registry-kafka-es:
    image: aas-registry-test/aas-registry-dotaas-part2-kafka-es:0.3.0-SNAPSHOT
    container_name: aas-registry-kafka-es
    pull_policy: never
    ports:
      - "8020:8080"
    depends_on:
      - elasticsearch
      - kafka
    restart: always
    environment:
      ELASTICSEARCH_HOST_URL: elasticsearch:9200 
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    networks:
      - basyx


  aas-registry-kafka-es-external-conf:
    image: aas-registry-test/aas-registry-dotaas-part2-kafka-es:0.3.0-SNAPSHOT
    container_name: aas-registry-kafka-es-external-conf
    pull_policy: never
    ports:
      - "8024:8080"
    depends_on:
      - elasticsearch
      - kafka
    restart: always    
    volumes: 
    # here an example on how to apply configuration using a application.yml in the config folder
    # you can also use an import or locations
    # https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files
    # or specify the settings directly -> it will override the profile settings because of the property-overlay order
    # -> see https://docs.spring.io/spring-boot/docs/2.1.8.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config
      - ./aas-config:/workspace/config  # /workspace is the docker file working dir
    environment:
      ELASTICSEARCH_HOST_URL: elasticsearch:9200 
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      # We have multiple options to enable inMemory storage. For example:
      # SPRING_PROFILES_ACTIVE: kafkaEvents,inMemoryStorage
      # as we have profile specific properties in our resource folders
      REGISTRY_TYPE: inMemory
    networks:
      - basyx


  aas-registry-kafka-mem:
    image: aas-registry-test/aas-registry-dotaas-part2-kafka-mem:0.3.0-SNAPSHOT
    container_name: aas-registry-kafka-mem
    pull_policy: never
    ports:
      - "8030:8080"
    depends_on:
      - elasticsearch
      - kafka
    restart: always
    environment:
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
    networks:
      - basyx

  aas-registry-log-mem:
    image: aas-registry-test/aas-registry-dotaas-part2-log-mem:0.3.0-SNAPSHOT
    container_name: aas-registry-log-mem
    pull_policy: never
    ports:
      - "8040:8080"
    restart: always
    networks:
      - basyx

  aas-registry-log-es:
    image: aas-registry-test/aas-registry-dotaas-part2-log-es:0.3.0-SNAPSHOT
    container_name: aas-registry-log-es
    pull_policy: never
    ports:
      - "8050:8080"
    depends_on:
      - elasticsearch
    restart: always
    environment:
      ELASTICSEARCH_HOST_URL: elasticsearch:9200 
    networks:
      - basyx