---
events:
  sink:
springfox:
  documentation:
    open-api.v3.path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics"
logging:
  level:
    root: INFO
server:
  port: 8080
  servlet:
    contextPath: /
servlet:
  headers: []
spring:
  jackson:
    date-format: org.eclipse.basyx.aas.registry.service.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  cloud:
    stream:
      bindings:
        default:
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        aasRegistryBinding:
          destination: aas-registry
          content-type: application/json
          producer:
            partitionKeyExpression: payload.id
            partitionCount: 1            